version: '3.5'

services:
  db-email:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - proxynet

  web-sendemail:
    build: .
    command:  /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db-email
    env_file:
      - .env
    networks:
      - proxynet

networks:
  proxynet:
    name: EstudePlus-network