# Generated by Django 2.2.1 on 2019-06-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='senha',
        ),
    ]
